name: Build Core

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_clash_api,with_v2ray_api,with_gvisor

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.5

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b
          add-to-path: false
          local-cache: false

      - name: Build core with arm64, android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          VERSION=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CGO_ENABLED=1 CC=${CC} GOARCH=arm64 GOOS=android go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} ./cmd/sing-box

      - name: Build core with x64, windows
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          VERSION=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} ./cmd/sing-box

      - name: Post to channel with arm64, android
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          pip install pyTelegramBotAPI
          path="$GITHUB_WORKSPACE/sing-box"
          VERSION=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CAPTION=$(echo -e "sing-box version ${VERSION}\n\nEnvironment: go1.21.4 android/arm64\nTags: ${TAGS}\nCGO: enabled\n\n合并 SagerNet/sing-box 和 PuerNya/sing-box 的 outbound-providers，windows 请前往 [GitHub](https://github.com/jasmoli/sing-box/actions/runs/${{ github.run_id }}) 下载\n\ncommit: ${{ github.event.head_commit.message }}")
          python3 $GITHUB_WORKSPACE/.github/scripts/tg_bot.py "$BOT_TOKEN" "$CHANNEL_ID" "$path" "$CAPTION"

      - name: Upload artifact with arm64, android
        uses: actions/upload-artifact@v3
        with:
          name: sing-box_android
          path: sing-box

      - name: Upload artifact with x64, windows
        uses: actions/upload-artifact@v3
        with:
          name: sing-box_windows
          path: sing-box.exe
